apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::851725361780:role/Nodegroup
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::851725361780:role/github-actions-eks
      username: github-actions
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::851725361780:user/devops@vitalsteer.com
      username: devops-admin
      groups:
        - system:masters
