apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  ports:
    - name: frontend
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  selector:
    role: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    role: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      serviceAccountName: healthcare-sa
      containers:
        - name: frontend
          image: 851725361780.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_HOST
              value: mongo-svc.default.svc.cluster.local
            - name: MONGO_PORT
              value: "27017"